.TH NCDU 1 "September 10, 2008" "ncdu-git" "ncdu manual"

.SH NAME
\fBncdu \fP- NCurses Disk Usage

.SH SYNOPSIS
\fBncdu\fP [\fB-hqvx\fP] [\fB--exclude PATTERN\fP] [\fB-X FILE\fP] \fIdir\fP

.SH DESCRIPTION
\fBncdu\fP (NCurses Disk Usage) is a curses-based version of
the well-known 'du', and provides a fast way to see what
directories are using your disk space.

.SH OPTIONS
.TP
\fB-h\fP
Print a small help message
.TP
\fB-q\fP
Quiet mode. While calculating disk space, \fBncdu\fP will
update the screen 10 times a second by default, this
will be decreased to once every 2 seconds in quiet
mode. Use this feature to save bandwidth over remote
connections.
.TP
\fB-v\fP
Print version.
.TP
\fB-x\fP
Only count files and directories on the same
filesystem as the specified \fIdir\fP.
.TP
\fB--exclude\fP PATTERN
Exclude files that match PATTERN. This argument can
be added multiple times to add more patterns.
.TP
\fB-X\fP FILE, \fB--exclude-from\fP FILE
Exclude files that match any pattern in FILE. Patterns
should be seperated by a newline.

.SH KEYS
.TP
\fB?\fP
Show help + keys + about screen
.TP
\fBup/down\fP
Cycle through the items
.TP
\fBright/enter\fP
Open selected directory
.TP
\fBleft\fP
Go to parent directory
.TP
\fBn\fP
Order by filename (press again for descending order)
.TP
\fBs\fP
Order by filesize (press again for descending order)
.TP
\fBa\fP
Toggle between showing disk usage and showing apparent size.
.TP
\fBd\fP
Delete the selected file or directory. An error message will be shown
when the contents of the directory do not match or do not exist anymore
on the filesystem.
.TP
\fBt\fP
Toggle dirs before files when sorting.
.TP
\fBg\fP
Toggle between showing percentage, graph, both, or none. Percentage
is relative to the size of the current directory, graph is relative
to the largest item in the current directory.
.TP
\fBh\fP
Show/hide 'hidden' or 'excluded' files and directories. Please note that
even though you can't see the hidden files and directories, they are still
there and they are still included in the directory sizes. If you suspect
that the totals shown at the bottom of the screen are not correct, make
sure you haven't enabled this option.
.TP
\fBi\fP
Show information about the current selected item.
.TP
\fBr\fP
Refresh/recalculate the current directory.
.TP
\fBq\fP
Quit

.SH AUTHOR
Written by Yoran Heling <projects@yorhel.nl>.

.SH BUGS
Infinite. Please contact the author if you find one.

.SH SEE ALSO
\fBdu\fP(1)
