.TH ncdu 1 "Nov 3, 2011" "ncdu-1.8" "ncdu manual"

=head1 NAME

B<ncdu> - NCurses Disk Usage


=head1 SYNOPSIS

B<ncdu> [I<options>] I<dir>


=head1 DESCRIPTION

ncdu (NCurses Disk Usage) is a curses-based version of the well-known 'du', and
provides a fast way to see what directories are using your disk space.


=head1 OPTIONS

=over

=item -h

Print a short help message.

=item -q

Quiet mode. While calculating disk space, ncdu will update the screen 10 times
a second by default, this will be decreased to once every 2 seconds in quiet
mode. Use this feature to save bandwidth over remote connections.

=item -0, -1, -2

Interface used to give feedback on scanning progress. C<-0> will prevent any
output from being displayed before ncdu is done scanning, while C<-1> will
display compact progress information on a single line of output. C<-2> presents
a full-screen ncurses interface while scanning (the default). C<-0> and C<-1> do
not initialize ncurses before the directory has been scanned, while C<-2> is the
only interface that provides feedback on recoverable errors. This does not
affect the interface used when re-scanning a directory from the ncurses
browser, where the full ncurses interface is always used.

=item -r

Read-only mode. This will disable the built-in file deletion feature.

=item -v

Print version.

=item -x

Only count files and directories on the same filesystem as the specified
I<dir>.

=item --exclude I<PATTERN>

Exclude files that match I<PATTERN>. This argument can be added multiple times
to add more patterns.

=item -X I<FILE>, --exclude-from I<FILE>

Exclude files that match any pattern in I<FILE>. Patterns should be separated
by a newline.

=back


=head1 KEYS

=over

=item ?

Show help + keys + about screen

=item up, down j, k

Cycle through the items

=item right, enter, l

Open selected directory

=item left, <, h

Go to parent directory

=item n

Order by filename (press again for descending order)

=item s

Order by filesize (press again for descending order)

=item a

Toggle between showing disk usage and showing apparent size.

=item d

Delete the selected file or directory. An error message will be shown when the
contents of the directory do not match or do not exist anymore on the
filesystem.

=item t

Toggle dirs before files when sorting.

=item g

Toggle between showing percentage, graph, both, or none. Percentage is relative
to the size of the current directory, graph is relative to the largest item in
the current directory.

=item e

Show/hide 'hidden' or 'excluded' files and directories. Please note that even
though you can't see the hidden files and directories, they are still there and
they are still included in the directory sizes. If you suspect that the totals
shown at the bottom of the screen are not correct, make sure you haven't
enabled this option.

=item i

Show information about the current selected item.

=item r

Refresh/recalculate the current directory.

=item q

Quit

=back


=head1 HARD LINKS

Every disk usage analysis utility has its own way of (not) counting hard links.
There does not seem to be any universally agreed method of handling hard links,
and it is even inconsistent among different versions of ncdu. This section
explains what each version of ncdu does.

ncdu 1.5 and below does not support any hard link detection at all: each link
is considered a separate inode and its size is counted for every link. This
means that the displayed directory sizes are incorrect when analyzing
directories which contain hard links.

ncdu 1.6 has basic hard link detection: When a link to a previously encountered
inode is detected, the link is considered to have a file size of zero bytes.
Its size is not counted again, and the link is indicated in the browser
interface with a 'H' mark. The displayed directory sizes are only correct when
all links to an inode reside within that directory. When this is not the case,
the sizes may or may not be correct, depending on which links were considered
as "duplicate" and which as "original". The indicated size of the topmost
directory (that is, the one specified on the command line upon starting ncdu)
is always correct.

ncdu 1.7 and later has improved hard link detection. Each file that has more
than two links has the "H" mark visible in the browser interface. Each hard
link is counted exactly once for every directory it appears in. The indicated
size of each directory is therefore, correctly, the sum of the sizes of all
unique inodes that can be found in that directory. Note, however, that this may
not always be same as the space that will be reclaimed after deleting the
directory, as some inodes may still be accessible from hard links outside it.


=head1 BUGS

Directory hard links are not supported. They will not be detected as being hard
links, and will thus be scanned and counted multiple times.

Some minor glitches may appear when displaying filenames that contain multibyte
or multicolumn characters.

Please report any other bugs you may find at the bug tracker, which can be
found on the web site at http://dev.yorhel.nl/ncdu


=head1 AUTHOR

Written by Yoran Heling <projects@yorhel.nl>.


=head1 SEE ALSO

L<du(1)>
